import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

import "./globals.css";
import Script from "next/script";

const albertSans = Albert_Sans({
	variable: "--font-albert-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${albertSans.variable} antialiased`}
			>
				<Navbar />
				<main>{children}</main>
				<Script
					id="hs-script-loader"
					src="//js.hs-scripts.com/53298.js"
					strategy="lazyOnload"
					async
					defer
				/>
				<Footer />
			</body>
		</html>
	);
}
